name: ci

on:
  push:
    branches: [ "dev", "stable" ]
  pull_request:
    branches: [ "dev", "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.info.os }}
    timeout-minutes: 18
    strategy:
      fail-fast: false
      matrix:
        info:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu",  cross: false, }
          - { os: "ubuntu-latest", target: "aarch64-unknown-linux-gnu", cross: true,  }
          - { os: "macos-12",      target: "x86_64-apple-darwin",       cross: false, }
          - { os: "windows-2019",  target: "x86_64-pc-windows-msvc",    cross: false, }
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.2.4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=${{ matrix.info.target }}
        use-cross: ${{ matrix.info.cross }}
    - name: Run tests
      run: cargo test --verbose
